/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryInput = IDL.Record({
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const DiscountType = IDL.Variant({
  'fixed' : IDL.Null,
  'percentage' : IDL.Null,
});
export const CouponInput = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiresAt' : IDL.Opt(IDL.Int),
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Opt(IDL.Nat),
});
export const Coupon = IDL.Record({
  'id' : IDL.Nat,
  'discountValue' : IDL.Nat,
  'expiresAt' : IDL.Opt(IDL.Int),
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'discountType' : DiscountType,
  'isActive' : IDL.Bool,
  'currentUses' : IDL.Nat,
  'maxUses' : IDL.Opt(IDL.Nat),
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : CategoryId,
  'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'price' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const ProductId = IDL.Nat;
export const ReviewId = IDL.Nat;
export const AddReviewResult = IDL.Variant({
  'ok' : ReviewId,
  'err' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const AdminUserView = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'securityQuestion' : IDL.Text,
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'phone' : IDL.Text,
  'wishlist' : IDL.Vec(ProductId),
  'avatar' : IDL.Opt(IDL.Text),
});
export const AdminUserUpdate = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Opt(IDL.Text),
  'newPassword' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const AuthResult = IDL.Variant({
  'ok' : IDL.Text,
  'invalidSecurityAnswer' : IDL.Null,
  'emailTaken' : IDL.Null,
  'resetTokenNotFound' : IDL.Null,
  'notFound' : IDL.Null,
  'resetTokenExpired' : IDL.Null,
  'invalidCredentials' : IDL.Null,
  'passwordResetSuccess' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const ConfirmPaymentInput = IDL.Record({
  'orderId' : IDL.Nat,
  'paymentIntentId' : IDL.Text,
});
export const CreatePaymentIntentInput = IDL.Record({
  'orderId' : IDL.Nat,
  'currency' : IDL.Text,
  'customerEmail' : IDL.Text,
  'amountPaisa' : IDL.Nat,
});
export const StripePaymentStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'requiresPaymentMethod' : IDL.Null,
  'requiresConfirmation' : IDL.Null,
  'requiresAction' : IDL.Null,
  'processing' : IDL.Null,
  'unknown' : IDL.Null,
  'succeeded' : IDL.Null,
});
export const PaymentIntentResult = IDL.Record({
  'status' : StripePaymentStatus,
  'clientSecret' : IDL.Text,
  'paymentIntentId' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : CategoryId,
  'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'price' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'readyForPickup' : IDL.Null,
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'stripe' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'total' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'customerPrincipal' : IDL.Opt(IDL.Principal),
  'createdAt' : Timestamp,
  'orderId' : IDL.Text,
  'pointsEarned' : IDL.Opt(IDL.Nat),
  'couponDiscount' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'pointsRedeemed' : IDL.Opt(IDL.Nat),
  'customerEmail' : IDL.Text,
  'stripePaymentStatus' : IDL.Opt(StripePaymentStatus),
});
export const CustomerProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'cart' : IDL.Vec(CartItem),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'securityQuestion' : IDL.Text,
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'securityAnswer' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
  'wishlist' : IDL.Vec(ProductId),
  'avatar' : IDL.Opt(IDL.Text),
});
export const PromoAnnouncement = IDL.Record({
  'title' : IDL.Text,
  'isActive' : IDL.Bool,
  'message' : IDL.Text,
  'deliveryHours' : IDL.Text,
  'offerImageUrl' : IDL.Opt(IDL.Text),
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'productId' : ProductId,
  'reviewerName' : IDL.Text,
  'reviewerPrincipal' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const SiteContent = IDL.Record({
  'footerEmail' : IDL.Text,
  'footerSocialFacebook' : IDL.Text,
  'specialOccasionsDescription' : IDL.Text,
  'contactMapEmbed' : IDL.Text,
  'contactHours' : IDL.Text,
  'footerAddress' : IDL.Text,
  'footerPhone' : IDL.Text,
  'aboutTitle' : IDL.Text,
  'siteName' : IDL.Text,
  'specialOccasionsOfferings' : IDL.Text,
  'footerSocialInstagram' : IDL.Text,
  'aboutFoundedYear' : IDL.Text,
  'contactEmail' : IDL.Text,
  'specialOccasionsTitle' : IDL.Text,
  'logoImageUrl' : IDL.Text,
  'aboutTeamInfo' : IDL.Text,
  'aboutStory' : IDL.Text,
  'headerTagline' : IDL.Text,
  'footerSocialWhatsApp' : IDL.Text,
  'contactAddress' : IDL.Text,
  'aboutMission' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const StoreInitData = IDL.Record({
  'categories' : IDL.Vec(Category),
  'lowStockProducts' : IDL.Vec(Product),
  'recentOrders' : IDL.Vec(Order),
  'products' : IDL.Vec(Product),
  'siteContent' : SiteContent,
  'promoAnnouncement' : IDL.Opt(PromoAnnouncement),
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'deliveryNote' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'pointsToRedeem' : IDL.Opt(IDL.Nat),
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const RegisterInput = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'securityQuestion' : IDL.Text,
  'email' : IDL.Text,
  'securityAnswer' : IDL.Text,
  'phone' : IDL.Text,
});
export const ResetRequestResult = IDL.Variant({
  'ok' : IDL.Null,
  'notFound' : IDL.Null,
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'securityQuestion' : IDL.Opt(IDL.Text),
  'securityAnswer' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'avatar' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([CategoryInput], [CategoryId], []),
  'addCoupon' : IDL.Func([CouponInput], [Coupon], []),
  'addLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'addProduct' : IDL.Func([ProductInput], [ProductId], []),
  'addReview' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Text],
      [AddReviewResult],
      [],
    ),
  'addToWishlist' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
  'adminDeleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'adminGetUser' : IDL.Func([IDL.Text], [IDL.Opt(AdminUserView)], ['query']),
  'adminUpdateUser' : IDL.Func([IDL.Text, AdminUserUpdate], [IDL.Bool], []),
  'assignAdmin' : IDL.Func([IDL.Principal], [], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuthResult], []),
  'chatWithBakey' : IDL.Func([IDL.Text, IDL.Vec(ChatMessage)], [IDL.Text], []),
  'claimAdmin' : IDL.Func([], [IDL.Bool], []),
  'clearMyCart' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'confirmPayment' : IDL.Func([ConfirmPaymentInput], [IDL.Bool], []),
  'createPaymentIntent' : IDL.Func(
      [CreatePaymentIntentInput],
      [PaymentIntentResult],
      [],
    ),
  'deductLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
  'deleteCoupon' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteOrder' : IDL.Func([OrderId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAverageRating' : IDL.Func([ProductId], [IDL.Opt(IDL.Float64)], ['query']),
  'getBackendStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'hasCategories' : IDL.Bool,
          'productCount' : IDL.Nat,
          'categoryCount' : IDL.Nat,
          'hasProducts' : IDL.Bool,
          'hasAdmins' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], []),
  'getLowStockProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getMyCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getMyOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getMyPoints' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(CustomerProfile)], ['query']),
  'getMyWishlist' : IDL.Func([IDL.Text], [IDL.Vec(ProductId)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrdersByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductImage' : IDL.Func(
      [ProductId],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getProductImages' : IDL.Func(
      [ProductId],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getPromoAnnouncement' : IDL.Func(
      [],
      [IDL.Opt(PromoAnnouncement)],
      ['query'],
    ),
  'getReviewsByProduct' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getSecurityQuestion' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getStoreInitData' : IDL.Func([], [StoreInitData], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCustomerRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'logoutCustomer' : IDL.Func([IDL.Text], [], []),
  'placeOrder' : IDL.Func([OrderInput], [OrderId], []),
  'registerCustomer' : IDL.Func([RegisterInput], [AuthResult], []),
  'reinitializeIfEmpty' : IDL.Func([], [IDL.Bool], []),
  'removeFromWishlist' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
  'requestPasswordReset' : IDL.Func([IDL.Text], [ResetRequestResult], []),
  'resetPasswordWithSecurityQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AuthResult],
      [],
    ),
  'resetPasswordWithToken' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'saveMyCart' : IDL.Func([IDL.Text, IDL.Vec(CartItem)], [IDL.Bool], []),
  'setProductImage' : IDL.Func(
      [ProductId, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [IDL.Bool],
      [],
    ),
  'setProductImages' : IDL.Func(
      [ProductId, IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Bool],
      [],
    ),
  'setPromoAnnouncement' : IDL.Func([PromoAnnouncement], [], []),
  'setSiteContent' : IDL.Func([SiteContent], [], []),
  'updateCategory' : IDL.Func([CategoryId, CategoryInput], [IDL.Bool], []),
  'updateCoupon' : IDL.Func([IDL.Nat, CouponInput], [IDL.Bool], []),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, UpdateProfileInput],
      [AuthResult],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
  'uploadProductImage' : IDL.Func(
      [ProductId, IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      [],
    ),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  'validateToken' : IDL.Func([IDL.Text], [IDL.Opt(CustomerProfile)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryInput = IDL.Record({
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const CategoryId = IDL.Nat;
  const DiscountType = IDL.Variant({
    'fixed' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const CouponInput = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiresAt' : IDL.Opt(IDL.Int),
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Opt(IDL.Nat),
  });
  const Coupon = IDL.Record({
    'id' : IDL.Nat,
    'discountValue' : IDL.Nat,
    'expiresAt' : IDL.Opt(IDL.Int),
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'discountType' : DiscountType,
    'isActive' : IDL.Bool,
    'currentUses' : IDL.Nat,
    'maxUses' : IDL.Opt(IDL.Nat),
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : CategoryId,
    'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'price' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const ProductId = IDL.Nat;
  const ReviewId = IDL.Nat;
  const AddReviewResult = IDL.Variant({ 'ok' : ReviewId, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const AdminUserView = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'securityQuestion' : IDL.Text,
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'phone' : IDL.Text,
    'wishlist' : IDL.Vec(ProductId),
    'avatar' : IDL.Opt(IDL.Text),
  });
  const AdminUserUpdate = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Opt(IDL.Text),
    'newPassword' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const AuthResult = IDL.Variant({
    'ok' : IDL.Text,
    'invalidSecurityAnswer' : IDL.Null,
    'emailTaken' : IDL.Null,
    'resetTokenNotFound' : IDL.Null,
    'notFound' : IDL.Null,
    'resetTokenExpired' : IDL.Null,
    'invalidCredentials' : IDL.Null,
    'passwordResetSuccess' : IDL.Null,
  });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const ConfirmPaymentInput = IDL.Record({
    'orderId' : IDL.Nat,
    'paymentIntentId' : IDL.Text,
  });
  const CreatePaymentIntentInput = IDL.Record({
    'orderId' : IDL.Nat,
    'currency' : IDL.Text,
    'customerEmail' : IDL.Text,
    'amountPaisa' : IDL.Nat,
  });
  const StripePaymentStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'requiresPaymentMethod' : IDL.Null,
    'requiresConfirmation' : IDL.Null,
    'requiresAction' : IDL.Null,
    'processing' : IDL.Null,
    'unknown' : IDL.Null,
    'succeeded' : IDL.Null,
  });
  const PaymentIntentResult = IDL.Record({
    'status' : StripePaymentStatus,
    'clientSecret' : IDL.Text,
    'paymentIntentId' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : CategoryId,
    'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'price' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'readyForPickup' : IDL.Null,
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'cod' : IDL.Null, 'stripe' : IDL.Null });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'total' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'customerPrincipal' : IDL.Opt(IDL.Principal),
    'createdAt' : Timestamp,
    'orderId' : IDL.Text,
    'pointsEarned' : IDL.Opt(IDL.Nat),
    'couponDiscount' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'pointsRedeemed' : IDL.Opt(IDL.Nat),
    'customerEmail' : IDL.Text,
    'stripePaymentStatus' : IDL.Opt(StripePaymentStatus),
  });
  const CustomerProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'cart' : IDL.Vec(CartItem),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'securityQuestion' : IDL.Text,
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'securityAnswer' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
    'wishlist' : IDL.Vec(ProductId),
    'avatar' : IDL.Opt(IDL.Text),
  });
  const PromoAnnouncement = IDL.Record({
    'title' : IDL.Text,
    'isActive' : IDL.Bool,
    'message' : IDL.Text,
    'deliveryHours' : IDL.Text,
    'offerImageUrl' : IDL.Opt(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'productId' : ProductId,
    'reviewerName' : IDL.Text,
    'reviewerPrincipal' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const SiteContent = IDL.Record({
    'footerEmail' : IDL.Text,
    'footerSocialFacebook' : IDL.Text,
    'specialOccasionsDescription' : IDL.Text,
    'contactMapEmbed' : IDL.Text,
    'contactHours' : IDL.Text,
    'footerAddress' : IDL.Text,
    'footerPhone' : IDL.Text,
    'aboutTitle' : IDL.Text,
    'siteName' : IDL.Text,
    'specialOccasionsOfferings' : IDL.Text,
    'footerSocialInstagram' : IDL.Text,
    'aboutFoundedYear' : IDL.Text,
    'contactEmail' : IDL.Text,
    'specialOccasionsTitle' : IDL.Text,
    'logoImageUrl' : IDL.Text,
    'aboutTeamInfo' : IDL.Text,
    'aboutStory' : IDL.Text,
    'headerTagline' : IDL.Text,
    'footerSocialWhatsApp' : IDL.Text,
    'contactAddress' : IDL.Text,
    'aboutMission' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const StoreInitData = IDL.Record({
    'categories' : IDL.Vec(Category),
    'lowStockProducts' : IDL.Vec(Product),
    'recentOrders' : IDL.Vec(Order),
    'products' : IDL.Vec(Product),
    'siteContent' : SiteContent,
    'promoAnnouncement' : IDL.Opt(PromoAnnouncement),
  });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'deliveryNote' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'pointsToRedeem' : IDL.Opt(IDL.Nat),
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const RegisterInput = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'securityQuestion' : IDL.Text,
    'email' : IDL.Text,
    'securityAnswer' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ResetRequestResult = IDL.Variant({
    'ok' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'securityQuestion' : IDL.Opt(IDL.Text),
    'securityAnswer' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'avatar' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([CategoryInput], [CategoryId], []),
    'addCoupon' : IDL.Func([CouponInput], [Coupon], []),
    'addLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'addProduct' : IDL.Func([ProductInput], [ProductId], []),
    'addReview' : IDL.Func(
        [ProductId, IDL.Text, IDL.Nat, IDL.Text],
        [AddReviewResult],
        [],
      ),
    'addToWishlist' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
    'adminDeleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'adminGetUser' : IDL.Func([IDL.Text], [IDL.Opt(AdminUserView)], ['query']),
    'adminUpdateUser' : IDL.Func([IDL.Text, AdminUserUpdate], [IDL.Bool], []),
    'assignAdmin' : IDL.Func([IDL.Principal], [], []),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AuthResult],
        [],
      ),
    'chatWithBakey' : IDL.Func(
        [IDL.Text, IDL.Vec(ChatMessage)],
        [IDL.Text],
        [],
      ),
    'claimAdmin' : IDL.Func([], [IDL.Bool], []),
    'clearMyCart' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'confirmPayment' : IDL.Func([ConfirmPaymentInput], [IDL.Bool], []),
    'createPaymentIntent' : IDL.Func(
        [CreatePaymentIntentInput],
        [PaymentIntentResult],
        [],
      ),
    'deductLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
    'deleteCoupon' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteOrder' : IDL.Func([OrderId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAverageRating' : IDL.Func(
        [ProductId],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getBackendStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'hasCategories' : IDL.Bool,
            'productCount' : IDL.Nat,
            'categoryCount' : IDL.Nat,
            'hasProducts' : IDL.Bool,
            'hasAdmins' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], []),
    'getLowStockProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getMyCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getMyOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getMyPoints' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getMyProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getMyWishlist' : IDL.Func([IDL.Text], [IDL.Vec(ProductId)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrdersByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductImage' : IDL.Func(
        [ProductId],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getProductImages' : IDL.Func(
        [ProductId],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getPromoAnnouncement' : IDL.Func(
        [],
        [IDL.Opt(PromoAnnouncement)],
        ['query'],
      ),
    'getReviewsByProduct' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getSecurityQuestion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getStoreInitData' : IDL.Func([], [StoreInitData], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCustomerRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'logoutCustomer' : IDL.Func([IDL.Text], [], []),
    'placeOrder' : IDL.Func([OrderInput], [OrderId], []),
    'registerCustomer' : IDL.Func([RegisterInput], [AuthResult], []),
    'reinitializeIfEmpty' : IDL.Func([], [IDL.Bool], []),
    'removeFromWishlist' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
    'requestPasswordReset' : IDL.Func([IDL.Text], [ResetRequestResult], []),
    'resetPasswordWithSecurityQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AuthResult],
        [],
      ),
    'resetPasswordWithToken' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'saveMyCart' : IDL.Func([IDL.Text, IDL.Vec(CartItem)], [IDL.Bool], []),
    'setProductImage' : IDL.Func(
        [ProductId, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [IDL.Bool],
        [],
      ),
    'setProductImages' : IDL.Func(
        [ProductId, IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Bool],
        [],
      ),
    'setPromoAnnouncement' : IDL.Func([PromoAnnouncement], [], []),
    'setSiteContent' : IDL.Func([SiteContent], [], []),
    'updateCategory' : IDL.Func([CategoryId, CategoryInput], [IDL.Bool], []),
    'updateCoupon' : IDL.Func([IDL.Nat, CouponInput], [IDL.Bool], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, UpdateProfileInput],
        [AuthResult],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
    'uploadProductImage' : IDL.Func(
        [ProductId, IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        [],
      ),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
    'validateToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };