/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddReviewResult = { 'ok' : ReviewId } |
  { 'err' : string };
export interface AdminUserUpdate {
  'bio' : [] | [string],
  'deliveryAddress' : [] | [string],
  'displayName' : [] | [string],
  'newPassword' : [] | [string],
  'phone' : [] | [string],
}
export interface AdminUserView {
  'bio' : [] | [string],
  'deliveryAddress' : [] | [string],
  'password' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'securityQuestion' : string,
  'email' : string,
  'loyaltyPoints' : bigint,
  'phone' : string,
  'wishlist' : Array<ProductId>,
  'avatar' : [] | [string],
}
export type AuthResult = { 'ok' : string } |
  { 'invalidSecurityAnswer' : null } |
  { 'emailTaken' : null } |
  { 'resetTokenNotFound' : null } |
  { 'notFound' : null } |
  { 'resetTokenExpired' : null } |
  { 'invalidCredentials' : null } |
  { 'passwordResetSuccess' : null };
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Category {
  'id' : CategoryId,
  'displayOrder' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export type CategoryId = bigint;
export interface CategoryInput {
  'displayOrder' : bigint,
  'name' : string,
  'description' : string,
}
export interface ChatMessage { 'content' : string, 'role' : string }
export interface ConfirmPaymentInput {
  'orderId' : bigint,
  'paymentIntentId' : string,
}
export interface Coupon {
  'id' : bigint,
  'discountValue' : bigint,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'createdAt' : bigint,
  'discountType' : DiscountType,
  'isActive' : boolean,
  'currentUses' : bigint,
  'maxUses' : [] | [bigint],
}
export interface CouponInput {
  'discountValue' : bigint,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'discountType' : DiscountType,
  'isActive' : boolean,
  'maxUses' : [] | [bigint],
}
export interface CreatePaymentIntentInput {
  'orderId' : bigint,
  'currency' : string,
  'customerEmail' : string,
  'amountPaisa' : bigint,
}
export interface CustomerProfile {
  'bio' : [] | [string],
  'deliveryAddress' : [] | [string],
  'cart' : Array<CartItem>,
  'name' : string,
  'createdAt' : Timestamp,
  'securityQuestion' : string,
  'email' : string,
  'loyaltyPoints' : bigint,
  'securityAnswer' : string,
  'passwordHash' : string,
  'phone' : string,
  'wishlist' : Array<ProductId>,
  'avatar' : [] | [string],
}
export type DiscountType = { 'fixed' : null } |
  { 'percentage' : null };
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'couponCode' : [] | [string],
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'customerPrincipal' : [] | [Principal],
  'createdAt' : Timestamp,
  'orderId' : string,
  'pointsEarned' : [] | [bigint],
  'couponDiscount' : [] | [bigint],
  'notes' : [] | [string],
  'stripePaymentIntentId' : [] | [string],
  'items' : Array<OrderItem>,
  'pointsRedeemed' : [] | [bigint],
  'customerEmail' : string,
  'stripePaymentStatus' : [] | [StripePaymentStatus],
}
export type OrderId = bigint;
export interface OrderInput {
  'customerName' : string,
  'deliveryAddress' : [] | [string],
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'deliveryNote' : [] | [string],
  'notes' : [] | [string],
  'pointsToRedeem' : [] | [bigint],
  'stripePaymentIntentId' : [] | [string],
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'readyForPickup' : null } |
  { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface PaymentIntentResult {
  'status' : StripePaymentStatus,
  'clientSecret' : string,
  'paymentIntentId' : string,
}
export type PaymentMethod = { 'cod' : null } |
  { 'stripe' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : CategoryId,
  'image' : [] | [Uint8Array],
  'price' : bigint,
  'ingredients' : Array<string>,
  'images' : Array<Uint8Array>,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'category' : CategoryId,
  'image' : [] | [Uint8Array],
  'price' : bigint,
  'ingredients' : Array<string>,
  'images' : Array<Uint8Array>,
}
export interface PromoAnnouncement {
  'title' : string,
  'isActive' : boolean,
  'message' : string,
  'deliveryHours' : string,
  'offerImageUrl' : [] | [string],
}
export interface RegisterInput {
  'password' : string,
  'name' : string,
  'securityQuestion' : string,
  'email' : string,
  'securityAnswer' : string,
  'phone' : string,
}
export type ResetRequestResult = { 'ok' : null } |
  { 'notFound' : null };
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'text' : string,
  'productId' : ProductId,
  'reviewerName' : string,
  'reviewerPrincipal' : Principal,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface SiteContent {
  'footerEmail' : string,
  'footerSocialFacebook' : string,
  'specialOccasionsDescription' : string,
  'contactMapEmbed' : string,
  'contactHours' : string,
  'footerAddress' : string,
  'footerPhone' : string,
  'aboutTitle' : string,
  'siteName' : string,
  'specialOccasionsOfferings' : string,
  'footerSocialInstagram' : string,
  'aboutFoundedYear' : string,
  'contactEmail' : string,
  'specialOccasionsTitle' : string,
  'logoImageUrl' : string,
  'aboutTeamInfo' : string,
  'aboutStory' : string,
  'headerTagline' : string,
  'footerSocialWhatsApp' : string,
  'contactAddress' : string,
  'aboutMission' : string,
  'contactPhone' : string,
}
export interface StoreInitData {
  'categories' : Array<Category>,
  'lowStockProducts' : Array<Product>,
  'recentOrders' : Array<Order>,
  'products' : Array<Product>,
  'siteContent' : SiteContent,
  'promoAnnouncement' : [] | [PromoAnnouncement],
}
export type StripePaymentStatus = { 'canceled' : null } |
  { 'requiresPaymentMethod' : null } |
  { 'requiresConfirmation' : null } |
  { 'requiresAction' : null } |
  { 'processing' : null } |
  { 'unknown' : null } |
  { 'succeeded' : null };
export type Timestamp = bigint;
export interface UpdateProfileInput {
  'bio' : [] | [string],
  'deliveryAddress' : [] | [string],
  'name' : [] | [string],
  'securityQuestion' : [] | [string],
  'securityAnswer' : [] | [string],
  'phone' : [] | [string],
  'avatar' : [] | [string],
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[CategoryInput], CategoryId>,
  'addCoupon' : ActorMethod<[CouponInput], Coupon>,
  'addLoyaltyPoints' : ActorMethod<[string, bigint], boolean>,
  'addProduct' : ActorMethod<[ProductInput], ProductId>,
  'addReview' : ActorMethod<
    [ProductId, string, bigint, string],
    AddReviewResult
  >,
  'addToWishlist' : ActorMethod<[string, ProductId], boolean>,
  'adminDeleteUser' : ActorMethod<[string], boolean>,
  'adminGetUser' : ActorMethod<[string], [] | [AdminUserView]>,
  'adminUpdateUser' : ActorMethod<[string, AdminUserUpdate], boolean>,
  'assignAdmin' : ActorMethod<[Principal], undefined>,
  'changePassword' : ActorMethod<[string, string, string], AuthResult>,
  'chatWithBakey' : ActorMethod<[string, Array<ChatMessage>], string>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'clearMyCart' : ActorMethod<[string], boolean>,
  'confirmPayment' : ActorMethod<[ConfirmPaymentInput], boolean>,
  'createPaymentIntent' : ActorMethod<
    [CreatePaymentIntentInput],
    PaymentIntentResult
  >,
  'deductLoyaltyPoints' : ActorMethod<[string, bigint], boolean>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteCoupon' : ActorMethod<[bigint], boolean>,
  'deleteOrder' : ActorMethod<[OrderId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAverageRating' : ActorMethod<[ProductId], [] | [number]>,
  'getBackendStatus' : ActorMethod<
    [],
    {
      'hasCategories' : boolean,
      'productCount' : bigint,
      'categoryCount' : bigint,
      'hasProducts' : boolean,
      'hasAdmins' : boolean,
    }
  >,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getLowStockProducts' : ActorMethod<[bigint], Array<Product>>,
  'getMyCart' : ActorMethod<[string], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[string], Array<Order>>,
  'getMyPoints' : ActorMethod<[string], bigint>,
  'getMyProfile' : ActorMethod<[string], [] | [CustomerProfile]>,
  'getMyWishlist' : ActorMethod<[string], Array<ProductId>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrdersByDateRange' : ActorMethod<[bigint, bigint], Array<Order>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductImage' : ActorMethod<[ProductId], [] | [Uint8Array]>,
  'getProductImages' : ActorMethod<[ProductId], Array<Uint8Array>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'getPromoAnnouncement' : ActorMethod<[], [] | [PromoAnnouncement]>,
  'getReviewsByProduct' : ActorMethod<[ProductId], Array<Review>>,
  'getSecurityQuestion' : ActorMethod<[string], [] | [string]>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getStoreInitData' : ActorMethod<[], StoreInitData>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCustomerRegistered' : ActorMethod<[string], boolean>,
  'listAllUsers' : ActorMethod<[], Array<AdminUserView>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'loginCustomer' : ActorMethod<[string, string], AuthResult>,
  'logoutCustomer' : ActorMethod<[string], undefined>,
  'placeOrder' : ActorMethod<[OrderInput], OrderId>,
  'registerCustomer' : ActorMethod<[RegisterInput], AuthResult>,
  'reinitializeIfEmpty' : ActorMethod<[], boolean>,
  'removeFromWishlist' : ActorMethod<[string, ProductId], boolean>,
  'requestPasswordReset' : ActorMethod<[string], ResetRequestResult>,
  'resetPasswordWithSecurityQuestion' : ActorMethod<
    [string, string, string],
    AuthResult
  >,
  'resetPasswordWithToken' : ActorMethod<[string, string], AuthResult>,
  'saveMyCart' : ActorMethod<[string, Array<CartItem>], boolean>,
  'setProductImage' : ActorMethod<[ProductId, [] | [Uint8Array]], boolean>,
  'setProductImages' : ActorMethod<[ProductId, Array<Uint8Array>], boolean>,
  'setPromoAnnouncement' : ActorMethod<[PromoAnnouncement], undefined>,
  'setSiteContent' : ActorMethod<[SiteContent], undefined>,
  'updateCategory' : ActorMethod<[CategoryId, CategoryInput], boolean>,
  'updateCoupon' : ActorMethod<[bigint, CouponInput], boolean>,
  'updateMyProfile' : ActorMethod<[string, UpdateProfileInput], AuthResult>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], boolean>,
  'uploadProductImage' : ActorMethod<[ProductId, Uint8Array], boolean>,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'validateToken' : ActorMethod<[string], [] | [CustomerProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];