/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CategoryInput {
    displayOrder: bigint;
    name: string;
    description: string;
}
export interface OrderItem {
    productId: ProductId;
    productName: string;
    quantity: bigint;
    unitPrice: bigint;
}
export interface OrderInput {
    customerName: string;
    deliveryAddress?: string;
    couponCode?: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    deliveryNote?: string;
    notes?: string;
    pointsToRedeem?: bigint;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
    customerEmail: string;
}
export interface PromoAnnouncement {
    title: string;
    isActive: boolean;
    message: string;
    deliveryHours: string;
    offerImageUrl?: string;
}
export interface RegisterInput {
    password: string;
    name: string;
    securityQuestion: string;
    email: string;
    securityAnswer: string;
    phone: string;
}
export interface ChatMessage {
    content: string;
    role: string;
}
export type ReviewId = bigint;
export interface SiteContent {
    footerEmail: string;
    footerSocialFacebook: string;
    specialOccasionsDescription: string;
    contactMapEmbed: string;
    contactHours: string;
    footerAddress: string;
    footerPhone: string;
    aboutTitle: string;
    siteName: string;
    specialOccasionsOfferings: string;
    footerSocialInstagram: string;
    aboutFoundedYear: string;
    contactEmail: string;
    specialOccasionsTitle: string;
    logoImageUrl: string;
    aboutTeamInfo: string;
    aboutStory: string;
    headerTagline: string;
    footerSocialWhatsApp: string;
    contactAddress: string;
    aboutMission: string;
    contactPhone: string;
}
export interface ConfirmPaymentInput {
    orderId: bigint;
    paymentIntentId: string;
}
export type AuthResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "invalidSecurityAnswer";
    invalidSecurityAnswer: null;
} | {
    __kind__: "emailTaken";
    emailTaken: null;
} | {
    __kind__: "resetTokenNotFound";
    resetTokenNotFound: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "resetTokenExpired";
    resetTokenExpired: null;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: null;
} | {
    __kind__: "passwordResetSuccess";
    passwordResetSuccess: null;
};
export interface StoreInitData {
    categories: Array<Category>;
    lowStockProducts: Array<Product>;
    recentOrders: Array<Order>;
    products: Array<Product>;
    siteContent: SiteContent;
    promoAnnouncement?: PromoAnnouncement;
}
export interface Review {
    id: ReviewId;
    createdAt: Timestamp;
    text: string;
    productId: ProductId;
    reviewerName: string;
    reviewerPrincipal: Principal;
    rating: bigint;
}
export interface Category {
    id: CategoryId;
    displayOrder: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
}
export interface ProductInput {
    name: string;
    description: string;
    category: CategoryId;
    image?: Uint8Array;
    price: bigint;
    ingredients: Array<string>;
    images: Array<Uint8Array>;
}
export type AddReviewResult = {
    __kind__: "ok";
    ok: ReviewId;
} | {
    __kind__: "err";
    err: string;
};
export interface PaymentIntentResult {
    status: StripePaymentStatus;
    clientSecret: string;
    paymentIntentId: string;
}
export interface Coupon {
    id: bigint;
    discountValue: bigint;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    discountType: DiscountType;
    isActive: boolean;
    currentUses: bigint;
    maxUses?: bigint;
}
export interface CustomerProfile {
    bio?: string;
    deliveryAddress?: string;
    cart: Array<CartItem>;
    name: string;
    createdAt: Timestamp;
    securityQuestion: string;
    email: string;
    loyaltyPoints: bigint;
    securityAnswer: string;
    passwordHash: string;
    phone: string;
    wishlist: Array<ProductId>;
    avatar?: string;
}
export interface CreatePaymentIntentInput {
    orderId: bigint;
    currency: string;
    customerEmail: string;
    amountPaisa: bigint;
}
export interface AdminUserUpdate {
    bio?: string;
    deliveryAddress?: string;
    displayName?: string;
    newPassword?: string;
    phone?: string;
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    couponCode?: string;
    total: bigint;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    customerPrincipal?: Principal;
    createdAt: Timestamp;
    orderId: string;
    pointsEarned?: bigint;
    couponDiscount?: bigint;
    notes?: string;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
    pointsRedeemed?: bigint;
    customerEmail: string;
    stripePaymentStatus?: StripePaymentStatus;
}
export interface AdminUserView {
    bio?: string;
    deliveryAddress?: string;
    password: string;
    name: string;
    createdAt: Timestamp;
    securityQuestion: string;
    email: string;
    loyaltyPoints: bigint;
    phone: string;
    wishlist: Array<ProductId>;
    avatar?: string;
}
export interface UpdateProfileInput {
    bio?: string;
    deliveryAddress?: string;
    name?: string;
    securityQuestion?: string;
    securityAnswer?: string;
    phone?: string;
    avatar?: string;
}
export type CategoryId = bigint;
export interface CouponInput {
    discountValue: bigint;
    expiresAt?: bigint;
    code: string;
    discountType: DiscountType;
    isActive: boolean;
    maxUses?: bigint;
}
export type ProductId = bigint;
export interface CartItem {
    productId: ProductId;
    quantity: bigint;
}
export type OrderId = bigint;
export interface Product {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    category: CategoryId;
    image?: Uint8Array;
    price: bigint;
    ingredients: Array<string>;
    images: Array<Uint8Array>;
}
export enum DiscountType {
    fixed = "fixed",
    percentage = "percentage"
}
export enum OrderStatus {
    readyForPickup = "readyForPickup",
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    outForDelivery = "outForDelivery",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    cod = "cod",
    stripe = "stripe"
}
export enum ResetRequestResult {
    ok = "ok",
    notFound = "notFound"
}
export enum StripePaymentStatus {
    canceled = "canceled",
    requiresPaymentMethod = "requiresPaymentMethod",
    requiresConfirmation = "requiresConfirmation",
    requiresAction = "requiresAction",
    processing = "processing",
    unknown_ = "unknown",
    succeeded = "succeeded"
}
export interface backendInterface {
    addCategory(input: CategoryInput): Promise<CategoryId>;
    addCoupon(input: CouponInput): Promise<Coupon>;
    addLoyaltyPoints(token: string, points: bigint): Promise<boolean>;
    addProduct(input: ProductInput): Promise<ProductId>;
    addReview(productId: ProductId, reviewerName: string, rating: bigint, text: string): Promise<AddReviewResult>;
    addToWishlist(token: string, productId: ProductId): Promise<boolean>;
    adminDeleteUser(email: string): Promise<boolean>;
    adminGetUser(email: string): Promise<AdminUserView | null>;
    adminUpdateUser(email: string, updates: AdminUserUpdate): Promise<boolean>;
    assignAdmin(user: Principal): Promise<void>;
    changePassword(token: string, currentPassword: string, newPassword: string): Promise<AuthResult>;
    chatWithBakey(userMessage: string, conversationHistory: Array<ChatMessage>): Promise<string>;
    claimAdmin(): Promise<boolean>;
    clearMyCart(token: string): Promise<boolean>;
    confirmPayment(input: ConfirmPaymentInput): Promise<boolean>;
    createPaymentIntent(input: CreatePaymentIntentInput): Promise<PaymentIntentResult>;
    deductLoyaltyPoints(token: string, points: bigint): Promise<boolean>;
    deleteCategory(id: CategoryId): Promise<boolean>;
    deleteCoupon(id: bigint): Promise<boolean>;
    deleteOrder(id: OrderId): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getAverageRating(productId: ProductId): Promise<number | null>;
    getBackendStatus(): Promise<{
        hasCategories: boolean;
        productCount: bigint;
        categoryCount: bigint;
        hasProducts: boolean;
        hasAdmins: boolean;
    }>;
    getCategories(): Promise<Array<Category>>;
    getCoupons(): Promise<Array<Coupon>>;
    getLowStockProducts(threshold: bigint): Promise<Array<Product>>;
    getMyCart(token: string): Promise<Array<CartItem>>;
    getMyOrders(token: string): Promise<Array<Order>>;
    getMyPoints(token: string): Promise<bigint>;
    getMyProfile(token: string): Promise<CustomerProfile | null>;
    getMyWishlist(token: string): Promise<Array<ProductId>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getOrdersByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Order>>;
    getProductById(id: ProductId): Promise<Product | null>;
    getProductImage(id: ProductId): Promise<Uint8Array | null>;
    getProductImages(id: ProductId): Promise<Array<Uint8Array>>;
    getProducts(): Promise<Array<Product>>;
    getProductsByCategory(categoryId: CategoryId): Promise<Array<Product>>;
    getPromoAnnouncement(): Promise<PromoAnnouncement | null>;
    getReviewsByProduct(productId: ProductId): Promise<Array<Review>>;
    getSecurityQuestion(email: string): Promise<string | null>;
    getSiteContent(): Promise<SiteContent>;
    getStoreInitData(): Promise<StoreInitData>;
    isAdmin(user: Principal): Promise<boolean>;
    isCustomerRegistered(token: string): Promise<boolean>;
    listAllUsers(): Promise<Array<AdminUserView>>;
    listOrders(): Promise<Array<Order>>;
    loginCustomer(email: string, password: string): Promise<AuthResult>;
    logoutCustomer(token: string): Promise<void>;
    placeOrder(input: OrderInput): Promise<OrderId>;
    registerCustomer(input: RegisterInput): Promise<AuthResult>;
    reinitializeIfEmpty(): Promise<boolean>;
    removeFromWishlist(token: string, productId: ProductId): Promise<boolean>;
    requestPasswordReset(email: string): Promise<ResetRequestResult>;
    resetPasswordWithSecurityQuestion(email: string, answer: string, newPassword: string): Promise<AuthResult>;
    resetPasswordWithToken(tokenId: string, newPassword: string): Promise<AuthResult>;
    saveMyCart(token: string, items: Array<CartItem>): Promise<boolean>;
    setProductImage(id: ProductId, image: Uint8Array | null): Promise<boolean>;
    setProductImages(id: ProductId, images: Array<Uint8Array>): Promise<boolean>;
    setPromoAnnouncement(input: PromoAnnouncement): Promise<void>;
    setSiteContent(content: SiteContent): Promise<void>;
    updateCategory(id: CategoryId, input: CategoryInput): Promise<boolean>;
    updateCoupon(id: bigint, input: CouponInput): Promise<boolean>;
    updateMyProfile(token: string, updates: UpdateProfileInput): Promise<AuthResult>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<boolean>;
    updateProduct(id: ProductId, input: ProductInput): Promise<boolean>;
    uploadProductImage(id: ProductId, imageBytes: Uint8Array): Promise<boolean>;
    validateCoupon(code: string): Promise<Coupon | null>;
    validateToken(token: string): Promise<CustomerProfile | null>;
}
import type { AddReviewResult as _AddReviewResult, AdminUserUpdate as _AdminUserUpdate, AdminUserView as _AdminUserView, AuthResult as _AuthResult, CartItem as _CartItem, Category as _Category, CategoryId as _CategoryId, Coupon as _Coupon, CouponInput as _CouponInput, CustomerProfile as _CustomerProfile, DiscountType as _DiscountType, Order as _Order, OrderId as _OrderId, OrderInput as _OrderInput, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentIntentResult as _PaymentIntentResult, PaymentMethod as _PaymentMethod, Product as _Product, ProductId as _ProductId, ProductInput as _ProductInput, PromoAnnouncement as _PromoAnnouncement, ResetRequestResult as _ResetRequestResult, ReviewId as _ReviewId, SiteContent as _SiteContent, StoreInitData as _StoreInitData, StripePaymentStatus as _StripePaymentStatus, Timestamp as _Timestamp, UpdateProfileInput as _UpdateProfileInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategory(arg0: CategoryInput): Promise<CategoryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return result;
        }
    }
    async addCoupon(arg0: CouponInput): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoupon(to_candid_CouponInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Coupon_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoupon(to_candid_CouponInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Coupon_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addLoyaltyPoints(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addLoyaltyPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLoyaltyPoints(arg0, arg1);
            return result;
        }
    }
    async addProduct(arg0: ProductInput): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_ProductInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_ProductInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addReview(arg0: ProductId, arg1: string, arg2: bigint, arg3: string): Promise<AddReviewResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
                return from_candid_AddReviewResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
            return from_candid_AddReviewResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToWishlist(arg0: string, arg1: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0, arg1);
            return result;
        }
    }
    async adminDeleteUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminGetUser(arg0: string): Promise<AdminUserView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUser(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUser(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateUser(arg0: string, arg1: AdminUserUpdate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateUser(arg0, to_candid_AdminUserUpdate_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateUser(arg0, to_candid_AdminUserUpdate_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAdmin(arg0);
            return result;
        }
    }
    async changePassword(arg0: string, arg1: string, arg2: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1, arg2);
                return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1, arg2);
            return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async chatWithBakey(arg0: string, arg1: Array<ChatMessage>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.chatWithBakey(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatWithBakey(arg0, arg1);
            return result;
        }
    }
    async claimAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return result;
        }
    }
    async clearMyCart(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyCart(arg0);
            return result;
        }
    }
    async confirmPayment(arg0: ConfirmPaymentInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return result;
        }
    }
    async createPaymentIntent(arg0: CreatePaymentIntentInput): Promise<PaymentIntentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentIntent(arg0);
                return from_candid_PaymentIntentResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentIntent(arg0);
            return from_candid_PaymentIntentResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deductLoyaltyPoints(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deductLoyaltyPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductLoyaltyPoints(arg0, arg1);
            return result;
        }
    }
    async deleteCategory(arg0: CategoryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: OrderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAverageRating(arg0: ProductId): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBackendStatus(): Promise<{
        hasCategories: boolean;
        productCount: bigint;
        categoryCount: bigint;
        hasProducts: boolean;
        hasAdmins: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackendStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackendStatus();
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupons();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupons();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockProducts(arg0: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockProducts(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockProducts(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCart(arg0: string): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCart(arg0);
            return result;
        }
    }
    async getMyOrders(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPoints(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPoints(arg0);
            return result;
        }
    }
    async getMyProfile(arg0: string): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWishlist(arg0: string): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWishlist(arg0);
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByDateRange(arg0, arg1);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByDateRange(arg0, arg1);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductImage(arg0: ProductId): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductImage(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductImage(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductImages(arg0: ProductId): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductImages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductImages(arg0);
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: CategoryId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromoAnnouncement(): Promise<PromoAnnouncement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromoAnnouncement();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromoAnnouncement();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByProduct(arg0: ProductId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByProduct(arg0);
            return result;
        }
    }
    async getSecurityQuestion(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityQuestion(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityQuestion(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteContent(): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent();
            return result;
        }
    }
    async getStoreInitData(): Promise<StoreInitData> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreInitData();
                return from_candid_StoreInitData_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreInitData();
            return from_candid_StoreInitData_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCustomerRegistered(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCustomerRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCustomerRegistered(arg0);
            return result;
        }
    }
    async listAllUsers(): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginCustomer(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginCustomer(arg0, arg1);
                return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginCustomer(arg0, arg1);
            return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutCustomer(arg0);
            return result;
        }
    }
    async placeOrder(arg0: OrderInput): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_OrderInput_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_OrderInput_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerCustomer(arg0: RegisterInput): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0);
                return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0);
            return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async reinitializeIfEmpty(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reinitializeIfEmpty();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reinitializeIfEmpty();
            return result;
        }
    }
    async removeFromWishlist(arg0: string, arg1: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0, arg1);
            return result;
        }
    }
    async requestPasswordReset(arg0: string): Promise<ResetRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPasswordReset(arg0);
                return from_candid_ResetRequestResult_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPasswordReset(arg0);
            return from_candid_ResetRequestResult_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPasswordWithSecurityQuestion(arg0: string, arg1: string, arg2: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithSecurityQuestion(arg0, arg1, arg2);
                return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithSecurityQuestion(arg0, arg1, arg2);
            return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPasswordWithToken(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithToken(arg0, arg1);
                return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithToken(arg0, arg1);
            return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMyCart(arg0: string, arg1: Array<CartItem>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyCart(arg0, arg1);
            return result;
        }
    }
    async setProductImage(arg0: ProductId, arg1: Uint8Array | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setProductImage(arg0, to_candid_opt_n59(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProductImage(arg0, to_candid_opt_n59(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setProductImages(arg0: ProductId, arg1: Array<Uint8Array>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setProductImages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProductImages(arg0, arg1);
            return result;
        }
    }
    async setPromoAnnouncement(arg0: PromoAnnouncement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPromoAnnouncement(to_candid_PromoAnnouncement_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPromoAnnouncement(to_candid_PromoAnnouncement_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setSiteContent(arg0: SiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSiteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSiteContent(arg0);
            return result;
        }
    }
    async updateCategory(arg0: CategoryId, arg1: CategoryInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateCoupon(arg0: bigint, arg1: CouponInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoupon(arg0, to_candid_CouponInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoupon(arg0, to_candid_CouponInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMyProfile(arg0: string, arg1: UpdateProfileInput): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, to_candid_UpdateProfileInput_n62(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, to_candid_UpdateProfileInput_n62(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n64(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n64(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadProductImage(arg0: ProductId, arg1: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProductImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProductImage(arg0, arg1);
            return result;
        }
    }
    async validateCoupon(arg0: string): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateToken(arg0: string): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateToken(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateToken(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddReviewResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddReviewResult): AddReviewResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AdminUserView_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserView): AdminUserView {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerProfile): CustomerProfile {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentIntentResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentIntentResult): PaymentIntentResult {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PromoAnnouncement_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromoAnnouncement): PromoAnnouncement {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ResetRequestResult_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResetRequestResult): ResetRequestResult {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_StoreInitData_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreInitData): StoreInitData {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_StripePaymentStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripePaymentStatus): StripePaymentStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminUserView]): AdminUserView | null {
    return value.length === 0 ? null : from_candid_AdminUserView_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StripePaymentStatus]): StripePaymentStatus | null {
    return value.length === 0 ? null : from_candid_StripePaymentStatus_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : from_candid_CustomerProfile_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PromoAnnouncement]): PromoAnnouncement | null {
    return value.length === 0 ? null : from_candid_PromoAnnouncement_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : from_candid_Coupon_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    deliveryAddress: [] | [string];
    password: string;
    name: string;
    createdAt: _Timestamp;
    securityQuestion: string;
    email: string;
    loyaltyPoints: bigint;
    phone: string;
    wishlist: Array<_ProductId>;
    avatar: [] | [string];
}): {
    bio?: string;
    deliveryAddress?: string;
    password: string;
    name: string;
    createdAt: Timestamp;
    securityQuestion: string;
    email: string;
    loyaltyPoints: bigint;
    phone: string;
    wishlist: Array<ProductId>;
    avatar?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bio)),
        deliveryAddress: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.deliveryAddress)),
        password: value.password,
        name: value.name,
        createdAt: value.createdAt,
        securityQuestion: value.securityQuestion,
        email: value.email,
        loyaltyPoints: value.loyaltyPoints,
        phone: value.phone,
        wishlist: value.wishlist,
        avatar: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _StripePaymentStatus;
    clientSecret: string;
    paymentIntentId: string;
}): {
    status: StripePaymentStatus;
    clientSecret: string;
    paymentIntentId: string;
} {
    return {
        status: from_candid_StripePaymentStatus_n25(_uploadFile, _downloadFile, value.status),
        clientSecret: value.clientSecret,
        paymentIntentId: value.paymentIntentId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    createdAt: _Timestamp;
    description: string;
    category: _CategoryId;
    image: [] | [Uint8Array];
    price: bigint;
    ingredients: Array<string>;
    images: Array<Uint8Array>;
}): {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    category: CategoryId;
    image?: Uint8Array;
    price: bigint;
    ingredients: Array<string>;
    images: Array<Uint8Array>;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        image: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.image)),
        price: value.price,
        ingredients: value.ingredients,
        images: value.images
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    couponCode: [] | [string];
    total: bigint;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    customerPrincipal: [] | [Principal];
    createdAt: _Timestamp;
    orderId: string;
    pointsEarned: [] | [bigint];
    couponDiscount: [] | [bigint];
    notes: [] | [string];
    stripePaymentIntentId: [] | [string];
    items: Array<_OrderItem>;
    pointsRedeemed: [] | [bigint];
    customerEmail: string;
    stripePaymentStatus: [] | [_StripePaymentStatus];
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    couponCode?: string;
    total: bigint;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    customerPrincipal?: Principal;
    createdAt: Timestamp;
    orderId: string;
    pointsEarned?: bigint;
    couponDiscount?: bigint;
    notes?: string;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
    pointsRedeemed?: bigint;
    customerEmail: string;
    stripePaymentStatus?: StripePaymentStatus;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n36(_uploadFile, _downloadFile, value.status),
        couponCode: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.couponCode)),
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n38(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        customerPrincipal: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.customerPrincipal)),
        createdAt: value.createdAt,
        orderId: value.orderId,
        pointsEarned: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.pointsEarned)),
        couponDiscount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.couponDiscount)),
        notes: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notes)),
        stripePaymentIntentId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.stripePaymentIntentId)),
        items: value.items,
        pointsRedeemed: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.pointsRedeemed)),
        customerEmail: value.customerEmail,
        stripePaymentStatus: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.stripePaymentStatus))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    deliveryAddress: [] | [string];
    cart: Array<_CartItem>;
    name: string;
    createdAt: _Timestamp;
    securityQuestion: string;
    email: string;
    loyaltyPoints: bigint;
    securityAnswer: string;
    passwordHash: string;
    phone: string;
    wishlist: Array<_ProductId>;
    avatar: [] | [string];
}): {
    bio?: string;
    deliveryAddress?: string;
    cart: Array<CartItem>;
    name: string;
    createdAt: Timestamp;
    securityQuestion: string;
    email: string;
    loyaltyPoints: bigint;
    securityAnswer: string;
    passwordHash: string;
    phone: string;
    wishlist: Array<ProductId>;
    avatar?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bio)),
        deliveryAddress: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.deliveryAddress)),
        cart: value.cart,
        name: value.name,
        createdAt: value.createdAt,
        securityQuestion: value.securityQuestion,
        email: value.email,
        loyaltyPoints: value.loyaltyPoints,
        securityAnswer: value.securityAnswer,
        passwordHash: value.passwordHash,
        phone: value.phone,
        wishlist: value.wishlist,
        avatar: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    isActive: boolean;
    message: string;
    deliveryHours: string;
    offerImageUrl: [] | [string];
}): {
    title: string;
    isActive: boolean;
    message: string;
    deliveryHours: string;
    offerImageUrl?: string;
} {
    return {
        title: value.title,
        isActive: value.isActive,
        message: value.message,
        deliveryHours: value.deliveryHours,
        offerImageUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.offerImageUrl))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<_Category>;
    lowStockProducts: Array<_Product>;
    recentOrders: Array<_Order>;
    products: Array<_Product>;
    siteContent: _SiteContent;
    promoAnnouncement: [] | [_PromoAnnouncement];
}): {
    categories: Array<Category>;
    lowStockProducts: Array<Product>;
    recentOrders: Array<Order>;
    products: Array<Product>;
    siteContent: SiteContent;
    promoAnnouncement?: PromoAnnouncement;
} {
    return {
        categories: value.categories,
        lowStockProducts: from_candid_vec_n29(_uploadFile, _downloadFile, value.lowStockProducts),
        recentOrders: from_candid_vec_n33(_uploadFile, _downloadFile, value.recentOrders),
        products: from_candid_vec_n29(_uploadFile, _downloadFile, value.products),
        siteContent: value.siteContent,
        promoAnnouncement: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.promoAnnouncement))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    discountValue: bigint;
    expiresAt: [] | [bigint];
    code: string;
    createdAt: bigint;
    discountType: _DiscountType;
    isActive: boolean;
    currentUses: bigint;
    maxUses: [] | [bigint];
}): {
    id: bigint;
    discountValue: bigint;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    discountType: DiscountType;
    isActive: boolean;
    currentUses: bigint;
    maxUses?: bigint;
} {
    return {
        id: value.id,
        discountValue: value.discountValue,
        expiresAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        createdAt: value.createdAt,
        discountType: from_candid_DiscountType_n8(_uploadFile, _downloadFile, value.discountType),
        isActive: value.isActive,
        currentUses: value.currentUses,
        maxUses: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.maxUses))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ReviewId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ReviewId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    invalidSecurityAnswer: null;
} | {
    emailTaken: null;
} | {
    resetTokenNotFound: null;
} | {
    notFound: null;
} | {
    resetTokenExpired: null;
} | {
    invalidCredentials: null;
} | {
    passwordResetSuccess: null;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "invalidSecurityAnswer";
    invalidSecurityAnswer: null;
} | {
    __kind__: "emailTaken";
    emailTaken: null;
} | {
    __kind__: "resetTokenNotFound";
    resetTokenNotFound: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "resetTokenExpired";
    resetTokenExpired: null;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: null;
} | {
    __kind__: "passwordResetSuccess";
    passwordResetSuccess: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "invalidSecurityAnswer" in value ? {
        __kind__: "invalidSecurityAnswer",
        invalidSecurityAnswer: value.invalidSecurityAnswer
    } : "emailTaken" in value ? {
        __kind__: "emailTaken",
        emailTaken: value.emailTaken
    } : "resetTokenNotFound" in value ? {
        __kind__: "resetTokenNotFound",
        resetTokenNotFound: value.resetTokenNotFound
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "resetTokenExpired" in value ? {
        __kind__: "resetTokenExpired",
        resetTokenExpired: value.resetTokenExpired
    } : "invalidCredentials" in value ? {
        __kind__: "invalidCredentials",
        invalidCredentials: value.invalidCredentials
    } : "passwordResetSuccess" in value ? {
        __kind__: "passwordResetSuccess",
        passwordResetSuccess: value.passwordResetSuccess
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canceled: null;
} | {
    requiresPaymentMethod: null;
} | {
    requiresConfirmation: null;
} | {
    requiresAction: null;
} | {
    processing: null;
} | {
    unknown: null;
} | {
    succeeded: null;
}): StripePaymentStatus {
    return "canceled" in value ? StripePaymentStatus.canceled : "requiresPaymentMethod" in value ? StripePaymentStatus.requiresPaymentMethod : "requiresConfirmation" in value ? StripePaymentStatus.requiresConfirmation : "requiresAction" in value ? StripePaymentStatus.requiresAction : "processing" in value ? StripePaymentStatus.processing : "unknown" in value ? StripePaymentStatus.unknown : "succeeded" in value ? StripePaymentStatus.succeeded : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    readyForPickup: null;
} | {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "readyForPickup" in value ? OrderStatus.readyForPickup : "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "outForDelivery" in value ? OrderStatus.outForDelivery : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    stripe: null;
}): PaymentMethod {
    return "cod" in value ? PaymentMethod.cod : "stripe" in value ? PaymentMethod.stripe : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
}): ResetRequestResult {
    return "ok" in value ? ResetRequestResult.ok : "notFound" in value ? ResetRequestResult.notFound : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: null;
} | {
    percentage: null;
}): DiscountType {
    return "fixed" in value ? DiscountType.fixed : "percentage" in value ? DiscountType.percentage : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserView>): Array<AdminUserView> {
    return value.map((x)=>from_candid_AdminUserView_n16(_uploadFile, _downloadFile, x));
}
function to_candid_AdminUserUpdate_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminUserUpdate): _AdminUserUpdate {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CouponInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponInput): _CouponInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderInput_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PromoAnnouncement_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromoAnnouncement): _PromoAnnouncement {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileInput_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): _UpdateProfileInput {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Uint8Array | null): [] | [Uint8Array] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    category: CategoryId;
    image?: Uint8Array;
    price: bigint;
    ingredients: Array<string>;
    images: Array<Uint8Array>;
}): {
    name: string;
    description: string;
    category: _CategoryId;
    image: [] | [Uint8Array];
    price: bigint;
    ingredients: Array<string>;
    images: Array<Uint8Array>;
} {
    return {
        name: value.name,
        description: value.description,
        category: value.category,
        image: value.image ? candid_some(value.image) : candid_none(),
        price: value.price,
        ingredients: value.ingredients,
        images: value.images
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountValue: bigint;
    expiresAt?: bigint;
    code: string;
    discountType: DiscountType;
    isActive: boolean;
    maxUses?: bigint;
}): {
    discountValue: bigint;
    expiresAt: [] | [bigint];
    code: string;
    discountType: _DiscountType;
    isActive: boolean;
    maxUses: [] | [bigint];
} {
    return {
        discountValue: value.discountValue,
        expiresAt: value.expiresAt ? candid_some(value.expiresAt) : candid_none(),
        code: value.code,
        discountType: to_candid_DiscountType_n3(_uploadFile, _downloadFile, value.discountType),
        isActive: value.isActive,
        maxUses: value.maxUses ? candid_some(value.maxUses) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    deliveryAddress?: string;
    displayName?: string;
    newPassword?: string;
    phone?: string;
}): {
    bio: [] | [string];
    deliveryAddress: [] | [string];
    displayName: [] | [string];
    newPassword: [] | [string];
    phone: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        deliveryAddress: value.deliveryAddress ? candid_some(value.deliveryAddress) : candid_none(),
        displayName: value.displayName ? candid_some(value.displayName) : candid_none(),
        newPassword: value.newPassword ? candid_some(value.newPassword) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    deliveryAddress?: string;
    couponCode?: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    deliveryNote?: string;
    notes?: string;
    pointsToRedeem?: bigint;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
    customerEmail: string;
}): {
    customerName: string;
    deliveryAddress: [] | [string];
    couponCode: [] | [string];
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    deliveryNote: [] | [string];
    notes: [] | [string];
    pointsToRedeem: [] | [bigint];
    stripePaymentIntentId: [] | [string];
    items: Array<_OrderItem>;
    customerEmail: string;
} {
    return {
        customerName: value.customerName,
        deliveryAddress: value.deliveryAddress ? candid_some(value.deliveryAddress) : candid_none(),
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n55(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        deliveryNote: value.deliveryNote ? candid_some(value.deliveryNote) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        pointsToRedeem: value.pointsToRedeem ? candid_some(value.pointsToRedeem) : candid_none(),
        stripePaymentIntentId: value.stripePaymentIntentId ? candid_some(value.stripePaymentIntentId) : candid_none(),
        items: value.items,
        customerEmail: value.customerEmail
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    isActive: boolean;
    message: string;
    deliveryHours: string;
    offerImageUrl?: string;
}): {
    title: string;
    isActive: boolean;
    message: string;
    deliveryHours: string;
    offerImageUrl: [] | [string];
} {
    return {
        title: value.title,
        isActive: value.isActive,
        message: value.message,
        deliveryHours: value.deliveryHours,
        offerImageUrl: value.offerImageUrl ? candid_some(value.offerImageUrl) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    deliveryAddress?: string;
    name?: string;
    securityQuestion?: string;
    securityAnswer?: string;
    phone?: string;
    avatar?: string;
}): {
    bio: [] | [string];
    deliveryAddress: [] | [string];
    name: [] | [string];
    securityQuestion: [] | [string];
    securityAnswer: [] | [string];
    phone: [] | [string];
    avatar: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        deliveryAddress: value.deliveryAddress ? candid_some(value.deliveryAddress) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        securityQuestion: value.securityQuestion ? candid_some(value.securityQuestion) : candid_none(),
        securityAnswer: value.securityAnswer ? candid_some(value.securityAnswer) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        avatar: value.avatar ? candid_some(value.avatar) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    fixed: null;
} | {
    percentage: null;
} {
    return value == DiscountType.fixed ? {
        fixed: null
    } : value == DiscountType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cod: null;
} | {
    stripe: null;
} {
    return value == PaymentMethod.cod ? {
        cod: null
    } : value == PaymentMethod.stripe ? {
        stripe: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    readyForPickup: null;
} | {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.readyForPickup ? {
        readyForPickup: null
    } : value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
